### ISSUE TITLE
[Meta] Roadmap

### ISSUE THREAD

**Issue by Decipher** [Decipher/example-druxt-blog#3]
- [ ] #7
  - [x] Header
  - [ ] Content
  - [ ] Sidebar
  - [x] Footer
  - [ ] "Layout builder"
- [ ] Theming
  - [ ] Daisy UI Form fields
  - [ ] Daisy UI components / paragraphs
- [ ] Content
  - [ ] #5
  - [ ] Paragraphs
  - [ ] Drag'n'Drop editbar
- [ ] Testing framwork
  - [ ] Unit tests
  - [ ] Code coverage
  - [ ] Cypress
- [ ] Documentation
